package com.revature.dao;

import com.revature.model.User;
import com.revature.utilty.ConnectionUtility;

import java.sql.*;

public class UserDao {
    public User createUser(User user) throws SQLException {
        // Try-with resources
        // whatever object is being used within the () will automatically be closed
        // whenever the try-with-resources is done executing OR an exception occurs
         try(Connection con = ConnectionUtility.createConnection()) {
             PreparedStatement pstmt = con.prepareStatement("INSERT INTO climawatch.users (username, name, email, password) VALUES(?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
             pstmt.setString(1, user.getUsername());
             pstmt.setString(2, user.getName());
             pstmt.setString(3, user.getEmail());
             pstmt.setString(4, user.getPassword());
             // executeUpdate is used to execute DML statements
             // Particularly INSERT, UPDATE and DELETE
             int numberOfRecordsInserted = pstmt.executeUpdate();
             // Retrieve autoGenerated snum serial
             ResultSet rs =pstmt.getGeneratedKeys();
             rs.next(); // moves the cursor to the next row in the ResultSet
            int autoGeneratedSnum =  rs.getInt(1);
            return new User(autoGeneratedSnum, user.getUsername(), user.getName(), user.getEmail(), user.getPassword());
        }
    }
}
